In [36]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA
import scipy.linalg
import numpy as np

In [38]:
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
X_centered=X-X_mean
pca=PCA(n_components=3)
X_reduced = pca.fit_transform(iris.data)
U,s,Vh=scipy.linalg.svd(X_centered)
X_reduced2=X_centered.dot(np.asmatrix(Vh).H[:,:3])
print(X_reduced)
print(X_reduced2)

In [41]:
print(pca.singular_values_**2/(len(X)-1))
print(pca.explained_variance_)

[4.22824171 0.24267075 0.0782095 ]
[4.22824171 0.24267075 0.0782095 ]


In [44]:
print(pca.components_)
print(Vh[:3])

[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]
 [ 0.58202985 -0.59791083 -0.07623608 -0.54583143]]
